execute pathogen#infect()
filetype plugin indent on
syntax enable
set background=light
let g:solarized_termtrans=1
colorscheme solarized
set rnu
set number
set hlsearch
set incsearch
autocmd VimLeave * call system("xclip -selection c", getreg('+'))
set clipboard=unnamedplus
