filetype plugin indent on
syntax enable
set background=light
colorscheme solarized
set rnu
set number
set hlsearch
set incsearch
autocmd VimLeave * call system("xclip -selection c", getreg('+'))
execute pathogen#infect()
